### ISSUE TITLE
Ability to disable context menu or use Chromium context menu API

### ISSUE THREAD

**Issue by mike-orozco-tfs** [antomanc/bing-chat-sidebar-chrome-extension#11]
I think it would be useful to have a setting to enable or disable the context menu that shows up when you highlight text. Some users of this extension may not want the additional functionality.

I'd say disabled by default, but that's up for discussion.

Alternatively, could make use of Chromiums context menu API to integrate these options into the actual context menu instead of injecting a makeshift one into the DOM.

Open to feedback, and open to developing this functionality myself through a PR.

**Comment by antomanc** [comment]
There is already an option in the extension settings to disable it. However I didn't know about Chromiums context menu API, this is definitely a better way to display it. If you want you can add it by yourself, but this weekend I can also give it some hours, it's your choice 😁

**Comment by antomanc** [comment]
Thank you so much for your contribution ❤️
